### PR TITLE
Allow compiling with SDK 24 (Android 7)

### PR DESCRIPTION
**Pull request by virtualdj**
PR to allow to use the app with Android 7, too.

NOTE: It would be great to have the app available for SDK 21 and up (Android 5.0, like [the app core](https://github.com/eu-digital-green-certificates/dgca-app-core-android/pull/29)) but that requires lowering the `zxing` library version to 3.3.0 (see [here](https://github.com/journeyapps/zxing-android-embedded#older-sdk-versions)) and this breaks the code.

Additionally, also [KeyGenParameterSpec](https://github.com/ministero-salute/it-dgc-verificaC19-android/blob/bd1f51f5d99b1dbf81801c8e1a1ed09c77fc5543/app/src/main/java/it/ministerodellasalute/verificaC19/security/DefaultKeyStoreCryptor.kt#L25) requires at least API 23 and has to be reworked (out of my skills).

### CODE REVIEW

**Comment by astagi** [comment]
@virtualdj could you rebase your branch with develop in order to make CI passing? Thanks!

**Comment by virtualdj** [comment]
> 
> 
> @virtualdj could you rebase your branch with develop in order to make CI passing? Thanks!

It's not only a matter of rebasing, I think. The develop code has been modified and doesn't compile anymore...

**Comment by astagi** [comment]
@virtualdj I see these errors

```
> Task :app:l8DexDesugarLibDebug
Error: e: /home/runner/work/it-dgc-verificaC19-android/it-dgc-verificaC19-android/dgca-verifier-app-android/app/src/main/java/it/ministerodellasalute/verificaC19/ui/main/verification/VerificationViewModel.kt: (96, 51): Type mismatch: inferred type is ByteArray? but ByteArray was expected

Error: e: /home/runner/work/it-dgc-verificaC19-android/it-dgc-verificaC19-android/dgca-verifier-app-android/app/src/main/java/it/ministerodellasalute/verificaC19/ui/main/verification/VerificationViewModel.kt: (119, 40): Type mismatch: inferred type is ByteArray? but ByteArray was expected
```

and I think that realigning this code with `develop` branch should make CI passing.

**Comment by virtualdj** [comment]
Tried like so, seems to compile locally...

**Comment by astagi** [comment]
CI finally passes, this PR is now ready for review. Thank you @virtualdj

**Review by astagi — APPROVED** [review]

**Pull request merged**
