### PR TITLE
PR to allow stable lower minSDK = API Level 23 - MM6.0

### LINKED ISSUE #95: Change min sdk to 23
## Current Implementation

In this moment the app supports only Android versions >= 8 . 

## Suggested Enhancement

With [desugaring](https://developer.android.com/studio/write/java8-support#library-desugaring) and [downgrade](https://github.com/journeyapps/zxing-android-embedded#older-sdk-versions) of the zxing library is possible to downgrade the min sdk to 23 

## Expected Benefits
People with android version >= 6 can download the app from the store

### PR DESCRIPTION
**Pull request by rawmain**
Aligned dependencies to use java.time classes (_through Android Gradle Plugin 4.0+ desugaring_) & Zxing barcode scanner (_partial core library downgrade_) with API Level 23 - Android Marshmallow 6.0 .

Confirmed stable/OK on real devices (range API23->API30) without runtime issues.

_Side notice :_ Further minSDK downgrade to API Level 21 (Lollipop 5.0) - _minimum limit threshold according to DGC core decoder_ - is technically possible, but not recommended.

Android Keystore supports indeed AES only since API Level 23 - Marshmallow 6.0 .

Therefore, minSDK 21 would require to rewrite DefaultKeyStoreCryptor & SecurityWrapper : 

1. Generate RSA pair of keys (using deprecated KeyPairGeneratorSpec API)
2. Generate AES key (using default/other crypto provider)
3. Encrypt the AES key using RSA
4. Store the encrypted AES key in SharedPreferences

Besides, it would require anyway further checks in order to prevent KEY_ALIAS null exceptions on some pre-M legacy devices.

### CODE REVIEW

**Review by astagi — CHANGES_REQUESTED** [review]
Hey @rawmain we're testing this PR! Please consider these changes:

- Rebase this branch
- Use spaces instead of tabs
- Try to upgrade zxing to 3.6.0 as mentioned by @ilGimmy

**Comment by rawmain** [comment]
Hello @astagi 

> Hey @rawmain we're testing this PR! Please consider these changes:
> 
> * Rebase this branch
> * Use spaces instead of tabs
> * Try to upgrade zxing to 3.6.0 as mentioned by @ilGimmy

Performed some tests during the latest 2 days with SDK23+ devices. Relied on the latest code for IT VerificaC19 Android app + DGCA App Core Android ([_main branch - last commit 2d ago_](https://github.com/eu-digital-green-certificates/dgca-app-core-android)).

So I've just updated the PR after 'ministero-salute:develop' rebase = required fixes + "keep it simple" approach for the [**required changes in order to allow OK SDK23+**](https://github.com/ministero-salute/it-dgc-verificaC19-android/compare/develop...VC19tests:release/1.1.0) : 

- Kept zxing-android-embedded 4.2.0 implementation - disabling transitive dependency resolution

- Implementation override for zxing:core 3.3.2 (_default version for zxing-android-embedded 3.6.0 - discarded 3.3.3 because of build/test errors_) 

- Kept appcompat version 1.2.0 (_no need to override to 1.0.2_)

I've also kept buildToolsVersion '28.0.3' just as a warning check for app/build.gradle . 

It gets ignored indeed as it is below the minimum supported version (29.0.2) for Android Gradle Plugin 4.1.3 .

**Comment by astagi** [comment]
@rawmain I built a new apk for testing starting from your branch and submitted it to the team, let you know asap

**Comment by Light2288** [comment]
@astagi @rawmain just as a note, european implementation already lowered minimum sdk but had to revert in back when implementing business rules: https://github.com/eu-digital-green-certificates/dgca-verifier-app-android/commit/8dc344105fce69c351f367b670fad44e227a2f4b
please have a look at eurpean commit to see if something can be done and if sdk lowering is compatible with european development, as european business rules will be probably included in verificac19 in one of the next releases

**Comment by rawmain** [comment]
Hello @Light2288 

> @astagi @rawmain just as a note, european implementation already lowered minimum sdk but had to revert in back when implementing business rules: [eu-digital-green-certificates@8dc3441](https://github.com/eu-digital-green-certificates/dgca-verifier-app-android/commit/8dc344105fce69c351f367b670fad44e227a2f4b)
> please have a look at eurpean commit to see if something can be done and if sdk lowering is compatible with european development, as european business rules will be probably included in verificac19 in one of the next releases

An additional gradle dependency for jackson-datatype-jsr310 is required in order to lower minSDK again from API 26 (Oreo 8.0) to API 23 (Marshmallow 6.0).

It allows indeed Jackson to recognize Java 8 Date & Time API data types (JSR-310) when desugaring has been set/enabled in app/build.gradle + minSDK=23 & the dgca-verifier-app is running on Android 23<=API<26 devices.

Otherwise, an exception is raised.

--------------------

Therefore, according to the version (2.12.0) used for jackson-module-kotlin in dgca-verifier-app & dgc-certlogic, minSDK of dgca-verifier-app can be lowered again to 23 by adding in app/build.gradle 

`implementation("com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.12.0")`

or by buildSrc dependencies/versions rearrangement of dgca-verifier-app & dgc-certlogic.

--------------------

In August, reference app's maintainers found it more convenient to revert minSDK to 26, since national apps' developers were still free / able to set lower minSDK for their own specific builds - https://github.com/eu-digital-green-certificates/dgca-verifier-app-android/issues/175#issuecomment-891587370 .

I've made anyway [some minor changes](https://github.com/rawmain/dgca-verifier-app-android-RM/releases/tag/1.1.15-RC-1-API23) to the reference dgca-verifier-app code in order to lower again minSDK back to 23.

Until now I haven't got any exceptions while building the ACC/TST variants & testing them on real devices API 23+. 

Therefore, I've just submitted a pull request - https://github.com/eu-digital-green-certificates/dgca-verifier-app-android/pull/202 - in order to allow the mantainers to check it again.

**Comment by astagi** [comment]
Great catch @rawmain!

**Review by astagi — APPROVED** [review]

**Comment by rawmain** [comment]
Hello @astagi & @Light2288 

I've just (slightly) rearranged Zxing-Core + jackson-datatype-jsr310 explicit dependencies in order to keep OK API23+ devices also with DGC-SDK integration.

Since the [it-dgc-verificac19-sdk-android](https://github.com/ministero-salute/it-dgc-verificac19-sdk-android) Repo is still private, I've performed the new compliance checks on the develop-candidate branch + my own (raw) implementation of DGC-SDK.

https://github.com/VC19tests/VC19-SDK-Test 

----------------------

These are my latest sample releases (minSDK API24 & API23) based on the develop-candidate branch code. 

Since still working with unofficial/test code I've just disabled the DGC-SDK version checks when the app starts.

- **minSDK API23** : https://github.com/VC19bkp/it-dgc-verificaC19-android-SDKtest/releases/tag/1.1.2-SDK-Test-API23

- **minSDK API24** : https://github.com/VC19bkp/it-dgc-verificaC19-android-SDKtest/releases/tag/1.1.2-SDK-Test

----------------------

_**EDIT :**_ API23->30 Tests OK on real devices also with the latest code updates (October 12th) in develop (default) branch, that added DGC-SDK + settings panel + totem mode + main/front camera switch + torch .

- **minSDK API23** : https://github.com/VC19bkp/it-dgc-verificaC19-android-SDKtest/releases/tag/1.1.2-SDK-Test-API23-01

**Comment by rawmain** [comment]
Hello @astagi & @Light2288 

API23->30 Tests OK on real devices also with the latest code updates (October 13th) in develop (default) branch + official IT DGC SDK code.

It hasn't required changes on IT DGC SDK code, apart from updating the versionName in sdk\build.gradle from 1.1.0 to 1.1.2 (_[related PR already submitted](https://github.com/ministero-salute/it-dgc-verificac19-sdk-android/pull/20)_).

- minSDK API23 with official IT DGC-SDK integration
https://github.com/VC19tests/verificaC19-android-lower-minSDK/releases/tag/develop-1.1.2-SDK-API23-20211013

**Comment by rawmain** [comment]
27/01/2023 - Completati check allineamento con upgrade compile/target ad API 33 di whitelabel-app 1.3.3 + DGC-SDK 1.1.1 : 

- Aggiunta esplicitazione `iterator()` in DebugInfoActivity, onde evitare la confusione tra la funzione Kotlin Iterable.forEach e la funzione Java8 forEach durante il desugaring in buildtime

- Aggiunti force di alcune dipendenze progetto/moduli in `build.gradle` top level, onde fixare funzionamento in runtime del decoder DGCA quando l'app viene usata con desugaring API <26

**Pull request closed without merging**
